### PR TITLE
updated snakefile naming and moved networks

### PR DESCRIPTION
**Pull request by etrieschman**
@ktehranchi -- I updated the naming scheme to incorporate hours into our design.

Unfortunately, I ran into an issue in the `run operations model.py` file that I couldn't solve, related to an error 
> ValueError: assignment destination is read-only

Have you encountered this before? It's being triggered by the row78 call of `process_iteration`. 

I think once we fix that, the new code should run. Do you mind having a look at what it might be?

### CODE REVIEW

**Comment by etrieschman** [comment]
> @etrieschman My hunch is this issue is caused by how we are making the folders. Maybe when snakemake creates the folder automatically it is read-only? Maybe try making the folder with mkdir before the output file is written?
> 
> I can take a look later this evening.

Interesting idea. I just checked all the folders that snakemake creates -- all of them have read and write privileges

**Comment by ktehranchi** [comment]
Fixed the Parralel Process error with [aab266f](https://github.com/ktehranchi/ScenarioSelection_PCS/pull/9/commits/aab266f374ad227ce3223c682b747488626e77f2) 

The issue was with nhours being changed from an int to a string when we put it in the snakemake list. We needed to convert it back to an int!

**Comment by ktehranchi** [comment]
wait nevermind.... it ran once, but the same read-only error showed up again.

**Comment by ktehranchi** [comment]
So there were two main issues:
- different pypsa network versions. i updated rtsgmlc to pypsa 0.25.1.. you should update your environment
- For some reason pypsa-usa doesn't play well with more than one parallel job, even though the versions are the same. I put an if statement that turns off parallelization when running pypsa.... I'll need to figure that out another time.

**Comment by etrieschman** [comment]
Stellar -- i'm impressed you were able to track all of these down. So, is it save to merge onto main now? I'm supposed to merge because it's my PR, right?

**Comment by ktehranchi** [comment]
There is one last error that looks like it should be easy to find 

```
  File "/Users/kamrantehranchi/mambaforge/envs/scenario_selection/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: results/pypsa_usa/rand_3hrs/elec_s_gp_l2.0_mrandom_fpred.csv not found.
``` 

in the last rule....

**Comment by ktehranchi** [comment]
Okay, should be good to go but best to test one last time! i have meetings about to start for rest of day so i wont be able to get to this again today

**Comment by etrieschman** [comment]
@ktehranchi -- nice work on this, it now runs on my machine. Going to merge this pull request.

**Pull request merged**
